name: Test Artifact Upload
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create test file
        run: echo "Hello World" > test.txt
        
      - name: Upload test file
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test.txt
