name: Unity Build and Release

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: '6000.0.32f1' 
        targetPlatform: 'StandaloneWindows64'
        buildTarget: 'StandaloneWindows64'
        buildPath: 'Build/Windows'
        projectPath: '.'
        unitySerial: ${{ secrets.UNITY_SERIAL }}

    - name: Generate Version
      id: version
      run: |
        # Create a version based on the current tag or commit hash
        VERSION="v$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: unity-build
        path: D:\Grigr3 - unity\MyFirstRepo\Build\Eclipsed_Relics.exe 
        

    - name: Create Release on GitHub
      id: create_release  # This ensures the step has an ID and its outputs can be referenced
      uses: gh actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        body: |
          - Version: ${{ env.VERSION }}
          - Description of the release.
          - Changelog or any notes you want to include in the release.
        draft: false
        prerelease: false

    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: unity-build

