name: Unity C v6# Style Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Check C# Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install CSharpier
        run: npm install --global csharpier
        
      - name: Run detailed style check
        run: |
          # Create a directory for the report
          mkdir -p style-report
          
          # Run CSharpier in verbose mode and capture output
          npx csharpier --check "Assets/**/*.cs" --verbose > style-report/detailed-output.txt || true
          
          # Generate a summary of file issues
          echo "# Files with style issues:" > style-report/summary.md
          grep "would be formatted" style-report/detailed-output.txt | sed 's/.*would be formatted: /- /' >> style-report/summary.md || echo "No formatting issues found" >> style-report/summary.md
          
          # Show the summary in the logs
          cat style-report/summary.md
          
      - name: Upload detailed report
        uses: actions/upload-artifact@v4
        with:
          name: style-report
          path: style-report
          retention-days: 30
