name: Unity testiing for the 100th time

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Run C# Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Lint C# code
        uses: JoshuaKGoldberg/lint-action@v2
        with:
          eslint: false
          prettier: false
          stylelint: false
          dotnet: true
          dotnetArgs: "--include Assets/Scripts/**/*.cs"
