name: Unity Basic Code Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Basic C# Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format
          
      - name: Run dotnet format
        run: dotnet format --verify-no-changes
